sequenceDiagram
    user->>browser: form input
    activate browser
    user->>browser: submit form

    Note right of user: The user fills the form's textfield and submits a new note by clicking the "Save" button

    browser->>server: POST https://studies.cs.helsinki.fi/exampleapp/new_note
    deactivate browser
    activate server

    Note right of browser: Form data is passed as the body of the request. The server adds the data as an object in the notes array

    server-->>browser: 302 status code
    deactivate server

    Note right of browser: The server asks the browser to do a new GET request, redirecting the app at the /notes header

    browser->>server: GET https://studies.cs.helsinki.fi/exampleapp/notes
    activate server
    server-->>browser: HTML document
    deactivate server

    browser->>server: GET https://studies.cs.helsinki.fi/exampleapp/main.css
    activate server
    server-->>browser: the css file
    deactivate server

    browser->>server: GET https://studies.cs.helsinki.fi/exampleapp/main.js
    activate server
    server-->>browser: the JavaScript file
    deactivate server

    browser->>server: GET https://studies.cs.helsinki.fi/exampleapp/data.json
    activate server
    server-->>browser: raw notes data as a JSON
    deactivate server